name: toast
description: "A new Flutter project."
 
 
publish_to: 'none'  
version: 1.0.0+1


environment:
  sdk: '>=3.2.4 <4.0.0'

 
#----------------------- PACKAGES -----------------------# 
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  gap_widget: ^0.0.1
  gap: ^3.0.1
  d_chart: ^2.6.7
  iconsax: ^0.0.8
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  unicons: ^2.1.1
  floating_frosted_bottom_bar: ^0.0.1
  glass: ^2.0.0+1
  flutter_advanced_segment: ^3.0.2


  # Storage Packages 
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0

  #Icons
  cupertino_icons: ^1.0.2


  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1   
  

#----------------------- PACKAGES End -----------------------#



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

 
 
flutter:  
  uses-material-design: true

   

#----------------------- LOCAL ASSETS -----------------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/images/onboarding/
    - assets/images/animations/
    - assets/images/Temp/
    - assets/images/TempFoodImages/
    # - assets/images/login_image.jpg
   


#----------------------- LOCAL FONTS -----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          style: italic
          weight: 400
   
   
   
   
   
   
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
   
   
   
