name: toast
description: "A new Flutter project."
 
 
publish_to: 'none'  
version: 1.0.0+1


environment:
  sdk: '>=3.2.4 <4.0.0'

 
#----------------------- PACKAGES -----------------------# 
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  gap_widget: ^0.0.1

  # Storage Packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0

  #Icons
  cupertino_icons: ^1.0.2


  # State Management



#----------------------- PACKAGES End -----------------------#



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

 
 
flutter:  
  uses-material-design: true

   

#----------------------- LOCAL ASSETS -----------------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
   


#----------------------- LOCAL FONTS -----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          style: italic
          weight: 400
   
   
   
   
   
   
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
   
   
   
