// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB023X03tnoB8E8mcjeffmgGzcp2alLdkM',
    appId: '1:81174192877:web:fe6402105735bfd288e2e4',
    messagingSenderId: '81174192877',
    projectId: 'toast-recipe-app',
    authDomain: 'toast-recipe-app.firebaseapp.com',
    storageBucket: 'toast-recipe-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyNe2yYNmNluyF-mYxzY7t8Yf0tXPYGk8',
    appId: '1:81174192877:android:1f45acb181972c6688e2e4',
    messagingSenderId: '81174192877',
    projectId: 'toast-recipe-app',
    storageBucket: 'toast-recipe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkVXZO6MJkNK6NInMFNOXgTPMqYNunH94',
    appId: '1:81174192877:ios:6fac94eeca66a0fb88e2e4',
    messagingSenderId: '81174192877',
    projectId: 'toast-recipe-app',
    storageBucket: 'toast-recipe-app.appspot.com',
    androidClientId: '81174192877-6m0npfh5tkdpvpbmqu0c89rmmq45ucv1.apps.googleusercontent.com',
    iosClientId: '81174192877-1r41b8uooal8sutk0np8k3ehvmojj1h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.toast',
  );
}
