// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSkq1FzzY_Jz_pFU_GwEaWNxReog898BY',
    appId: '1:819387602221:web:5f45111beedb5fe4696fa4',
    messagingSenderId: '819387602221',
    projectId: 'toast-askhalan',
    authDomain: 'toast-askhalan.firebaseapp.com',
    storageBucket: 'toast-askhalan.appspot.com',
    measurementId: 'G-4VHQDWCR4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC601PUnfIxGfxxfG1F-HGqDhV0xxsmiC8',
    appId: '1:819387602221:android:5171af96dca6ecfd696fa4',
    messagingSenderId: '819387602221',
    projectId: 'toast-askhalan',
    storageBucket: 'toast-askhalan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBsgIlWxqotgo8PeGmwVgXZMJwmWDOhX8',
    appId: '1:819387602221:ios:62a98b9c662dba68696fa4',
    messagingSenderId: '819387602221',
    projectId: 'toast-askhalan',
    storageBucket: 'toast-askhalan.appspot.com',
    iosBundleId: 'com.example.toast',
  );
}
